### ISSUE TITLE
Write a script to clean dir_result

### ISSUE THREAD

**Issue by CotterpinDoozer** [CancerRegistryOfNorway/nordcancore#21]
Joonas writes: 

> During running nordcan.R, sensitive data is saved into dir_result as before.
> It now occurs to me that those should probably be deleted at the end of the
> script when they are no longer needed. I would write a single function into
> perhaps "nordcancore" for this cleaning-up. Then at the end of the script there
> is simply this:

```
  # run this if you think you have finished here. this cleans up potentially
  # sensitive data in dir_result.
  nordcancore::clean_results(dir_result)
```
I think this is a good idea. The user should have the option to delete these data after having finished everything, and it is ok to leave it up to the user to do this or not.

**Comment by CotterpinDoozer** [comment]
Issue: Write a script to clean dir_result #21
Comment: Huidong will take this task. Estimate time: 0.5 hour.

**Comment by HuidongTian** [comment]
Updated. 

https://github.com/CancerRegistryOfNorway/nordcancore/blob/master/R/utils.R#L611
https://github.com/CancerRegistryOfNorway/NORDCAN/blob/master/nordcan_participant_instructions/nordcan.R#L322

**Comment by AnnaSkog** [comment]
Can I test this?
